name: network_manager
version: 0.0.0-dev.1

description:
  Provides a client to connect to NetworkManager - the service that manages network connections on Linux.

homepage: https://github.com/canonical/network_manager.dart

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  dbus: ^0.0.0-dev.17

dev_dependencies:
  pedantic: ^1.9.0
